### ISSUE TITLE
Get deployment working

### ISSUE THREAD

**Issue by DGKSK8LIFE** [DGKSK8LIFE/portfolio-source#10]

**Comment by xjcl** [comment]
You need to move all files to a new branch called `gh-pages`. Ideally also delete the `master` branch so it doesn't cause confusion. Then your website will be live on https://dgksk8life.github.io/portfolio-source after some minutes

**Comment by xjcl** [comment]
https://help.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

**Comment by DGKSK8LIFE** [comment]
already done; published on netlify forgot to close issue
